
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saidu
 */
public class EditDetails extends javax.swing.JFrame {
static public String confirmpass3="";
    /**
     * Creates new form EditDetails
     */

void edhukku2()
{
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from details";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                String  count=rs.getString("tablecount");
                String tax=rs.getString("tax");
                String servicetax=rs.getString("service");
                t1.setText(count);
                t2.setText(tax);
                t3.setText(servicetax);

                

            }
            double g1,g2,g3;
             g1=Double.parseDouble(t1.getText());
            g2=Double.parseDouble(t2.getText());
            g3=Double.parseDouble(t3.getText());
            l2.setText("Current values:- \n \n 1) Table count= "+g1+" \n 2) Tax= "+g2+"% \n 3) Service Tax="+g3+"% ");

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from companyname";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                String  count=rs.getString("name");
                
                t0.setText(count);

                

            }
            

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
}
    public EditDetails(String passe) {
        initComponents();
                 lback.setIcon(new javax.swing.ImageIcon("C:\\bg.jpg"));
linfo.setVisible(false);
        Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        setSize(sz.width,sz.height);
        confirmpass3=passe;
        edhukku2();
         try
        {
String nameu1="";
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from companyname";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
               nameu1=rs.getString("name");
               
            }
           ltitle.setText(nameu1+"");

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
         try {

			
			FileInputStream fin = new FileInputStream("C:\\background.txt");
                        BufferedReader br=new BufferedReader(new InputStreamReader(fin));
String s1=br.readLine();
			

lback.setIcon(new javax.swing.ImageIcon(s1)); 

		} catch (IOException e) {
			
		} 
       
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        linfo = new javax.swing.JLabel();
        bb = new javax.swing.JButton();
        l1 = new javax.swing.JScrollPane();
        l2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t0 = new javax.swing.JTextField();
        b01 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ltitle = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lback = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("<-- Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 110, 40);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("%");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 490, 30, 50);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Company Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 120, 170, 50);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Service Tax");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 490, 120, 50);

        t3.setNextFocusableComponent(bb);
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t3KeyReleased(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(250, 490, 90, 50);

        t1.setNextFocusableComponent(t2);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(250, 340, 90, 50);

        t2.setNextFocusableComponent(t3);
        getContentPane().add(t2);
        t2.setBounds(250, 420, 90, 50);

        linfo.setBackground(new java.awt.Color(255, 255, 255));
        linfo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        linfo.setOpaque(true);
        getContentPane().add(linfo);
        linfo.setBounds(760, 110, 550, 600);

        bb.setText("Update");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb);
        bb.setBounds(270, 620, 110, 40);

        l1.setViewportBorder(new javax.swing.border.MatteBorder(null));

        l2.setColumns(20);
        l2.setRows(5);
        l1.setViewportView(l2);

        getContentPane().add(l1);
        l1.setBounds(450, 320, 340, 240);

        jButton2.setText("Change Background");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(880, 320, 200, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("* If it doesnt work, run as administrator");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(930, 370, 390, 40);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Table Count");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 340, 120, 50);

        t0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t0.setEnabled(false);
        getContentPane().add(t0);
        t0.setBounds(530, 122, 350, 40);

        b01.setText("Click to edit");
        b01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b01ActionPerformed(evt);
            }
        });
        getContentPane().add(b01);
        b01.setBounds(900, 120, 180, 40);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 0));
        jLabel6.setText("Tax");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 420, 120, 50);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("%");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 420, 30, 50);

        ltitle.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        ltitle.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ltitle);
        ltitle.setBounds(510, 30, 420, 70);

        jButton3.setText("info");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1310, 710, 80, 40);

        lback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg8.jpg"))); // NOI18N
        lback.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbackMouseMoved(evt);
            }
        });
        lback.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbackKeyReleased(evt);
            }
        });
        getContentPane().add(lback);
        lback.setBounds(-6, -6, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        manager ll=new manager(confirmpass3);
        ll.setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
 try
{
    
    double g1,g2,g3;
    

              try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             
             g1=Double.parseDouble(t1.getText());
            g2=Double.parseDouble(t2.getText());
            g3=Double.parseDouble(t3.getText());
            if(g1>0&&g2>=0&&g3>=0)
            {
            String qry="update details set tablecount="+g1+",tax="+g2+",service="+g3+"";
            stmt.executeUpdate(qry);
            int c=JOptionPane.showOptionDialog(null, "Values Updated","Message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(c==JOptionPane.OK_OPTION)
                  {
                      t1.requestFocus();
                      
                      
                  }
            }
            else
            {
int c=JOptionPane.showOptionDialog(null, "Enter valid input","Message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(c==JOptionPane.OK_OPTION)
                  {
                       t1.requestFocus();
                      
                      
                  }            }
           
        
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
        
               
      
      
}
catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"enter valid values");
        }
        edhukku2();
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyReleased
    try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      bb.doClick();
     
   }
        }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_t3KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);

        File file = chooser.getSelectedFile();
        String fullPath = file.getAbsolutePath();

        lback.setText(fullPath);
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();

            String qry="insert into background values('"+fullPath+"')";
            stmt.executeUpdate(qry);

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());

        }
        try {

            FileOutputStream fop = new FileOutputStream("C:\\background.txt");

            // get the content in bytes
            byte[] b = fullPath.getBytes();

            fop.write(b);

            fop.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        try {

            FileInputStream fin = new FileInputStream("C:\\background.txt");
            BufferedReader br=new BufferedReader(new InputStreamReader(fin));
            String s1=br.readLine();

            
            lback.setIcon(new javax.swing.ImageIcon(s1));

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b01ActionPerformed
String cpname="";
        
        if(t0.isEnabled()==false)
{
    t0.setEnabled(true);
    b01.setText("Change Name");
}
else
{
    cpname=t0.getText();
     t0.setEnabled(false);
     b01.setText("Click to edit");
      try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             
            String qry="delete from companyname";
            stmt.executeUpdate(qry);
            
            
        
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
      
      
         try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            
                  String qry="insert into companyname values('"+cpname+"')";
                  stmt.executeUpdate(qry);
               
        
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
              try
        {
String nameu1="";
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from companyname";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
               nameu1=rs.getString("name");
               
            }
           ltitle.setText(nameu1+"");

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
}



        // TODO add your handling code here:
    }//GEN-LAST:event_b01ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
      jButton1.doClick();
      
   }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void lbackKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbackKeyReleased
linfo.setVisible(false);
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
      jButton1.doClick();
      
   }        // TODO add your handling code here:
    }//GEN-LAST:event_lbackKeyReleased

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        linfo.setVisible(true);
        linfo.setText("<html>\n" +
            "<head>\n" +
            "	<title>cafe</title>\n" +
            "</head>\n" +
            "<body><h1>gggggg</h1>\n" +
            "<p1> ggwp </p1>\n" +
            "\n" +
            "\n" +
            "</body>\n" +
            "</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lbackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbackMouseMoved
linfo.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lbackMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDetails(confirmpass3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b01;
    private javax.swing.JButton bb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane l1;
    private javax.swing.JTextArea l2;
    private javax.swing.JLabel lback;
    private javax.swing.JLabel linfo;
    private javax.swing.JLabel ltitle;
    private javax.swing.JTextField t0;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
