
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saidu
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
                 j1.setIcon(new javax.swing.ImageIcon("C:\\bg.jpg"));

        Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        setSize(sz.width,sz.height);
        j1.setIcon(new javax.swing.ImageIcon("C:\\bg.jpg"));
           try {

			
			FileInputStream fin = new FileInputStream("C:\\background.txt");
                        BufferedReader br=new BufferedReader(new InputStreamReader(fin));
String s1=br.readLine();
			

j1.setIcon(new javax.swing.ImageIcon(s1)); 

		} catch (IOException e) {
			
		} 
                try
        {
String nameu1="";
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from companyname";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
               nameu1=rs.getString("name");
               
            }
           ltitle.setText(nameu1+"");

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        l2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ltitle = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        j1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        bt1.setBackground(new java.awt.Color(0, 153, 153));
        bt1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1497366347_thefreeforty_register.png"))); // NOI18N
        bt1.setText("Login");
        bt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        bt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bt1KeyReleased(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(490, 490, 190, 60);

        l1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 51));
        l1.setText("PASSWORD :");
        getContentPane().add(l1);
        l1.setBounds(240, 390, 280, 40);

        t1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        t1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 102, 102)));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(530, 330, 260, 50);

        p1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        p1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 102, 102)));
        p1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p1KeyPressed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(530, 390, 260, 50);

        l2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        l2.setForeground(new java.awt.Color(51, 255, 255));
        l2.setText("USERNAME :");
        getContentPane().add(l2);
        l2.setBounds(230, 310, 290, 60);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("LOGIN PAGE");
        jLabel5.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 220, 320, 80);

        ltitle.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        ltitle.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ltitle);
        ltitle.setBounds(530, 60, 420, 70);

        jButton2.setText("info");
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1320, 720, 80, 40);

        jButton1.setText("Change manager account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(940, 560, 240, 50);

        j1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg8.jpg"))); // NOI18N
        j1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j1MouseMoved(evt);
            }
        });
        getContentPane().add(j1);
        j1.setBounds(0, 0, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       try
       {
        String pa,userid,pass,add,s1,man,wait;
        pa=new String(p1.getPassword());
        userid="";
        pass="";
        add="";
        man="manager";
        wait="cashier";
        
        s1=t1.getText();
        int k=0;        try
        {

            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from login";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                userid=rs.getString("userid");
                pass=rs.getString("password");
                add=rs.getString("desig");

                if(s1.equals(userid)&&pa.equals(pass)&&wait.equals(add))
                { k=1;
                    menu ff=new menu();
                    ff.setVisible(true);
                    setVisible(false);
                    

                }
                
                else if(s1.equals(userid)&&pa.equals(pass)&&man.equals(add))
                { k=1;
                    manager gg=new manager(pa);
                    gg.setVisible(true);
                     setVisible(false);

                }

            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        if(k==0)
        {
            JOptionPane.showMessageDialog(this,"Invalid username or password ");
        }
}catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased

       
        
             // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyReleased

    private void p1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1KeyPressed
         try
         {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      bt1.doClick();
   }
         }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_p1KeyPressed

    private void bt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt1KeyReleased
       try
       {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      bt1.doClick();
   }}catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1KeyReleased

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
manageracc asd=new manageracc();
asd.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseMoved
       // TODO add your handling code here:
    }//GEN-LAST:event_j1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JLabel j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel ltitle;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
