
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saidu
 */
public class manageracc extends javax.swing.JFrame {

    /**
     * Creates new form manageracc
     */
    public manageracc() {
        initComponents();
        j1.setIcon(new javax.swing.ImageIcon("C:\\bg.jpg"));
linfo.setVisible(false);
        Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        setSize(sz.width,sz.height);
        j1.setIcon(new javax.swing.ImageIcon("C:\\bg.jpg"));
           try {

			
			FileInputStream fin = new FileInputStream("C:\\background.txt");
                        BufferedReader br=new BufferedReader(new InputStreamReader(fin));
String s1=br.readLine();
			

j1.setIcon(new javax.swing.ImageIcon(s1)); 

		} catch (IOException e) {
			
		} 
                try
        {
String nameu1="";
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from companyname";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
               nameu1=rs.getString("name");
               
            }
           ltitle.setText(nameu1+"");

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linfo = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        pf2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        pf1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        tu1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tu0 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ltitle = new javax.swing.JLabel();
        lpp = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();
        lp1 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        linfo.setBackground(new java.awt.Color(255, 255, 255));
        linfo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        linfo.setOpaque(true);
        getContentPane().add(linfo);
        linfo.setBounds(760, 100, 550, 620);

        b5.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        b5.setText("Change Details");
        b5.setEnabled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b5KeyReleased(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(480, 530, 520, 60);

        pf2.setBackground(new java.awt.Color(204, 204, 204));
        pf2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        pf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf2ActionPerformed(evt);
            }
        });
        pf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pf2KeyReleased(evt);
            }
        });
        getContentPane().add(pf2);
        pf2.setBounds(660, 440, 270, 30);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("confirm passsword");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 440, 190, 30);

        pf1.setBackground(new java.awt.Color(204, 204, 204));
        pf1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        getContentPane().add(pf1);
        pf1.setBounds(660, 390, 270, 30);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 0));
        jLabel9.setText("passsword");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 390, 130, 30);

        tu1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        tu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu1ActionPerformed(evt);
            }
        });
        tu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tu1KeyReleased(evt);
            }
        });
        getContentPane().add(tu1);
        tu1.setBounds(660, 340, 270, 30);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 0));
        jLabel16.setText("User Id");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(470, 320, 80, 70);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 270, 100, 70);

        tu0.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        tu0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tu0KeyReleased(evt);
            }
        });
        getContentPane().add(tu0);
        tu0.setBounds(660, 290, 270, 30);

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 204));
        jLabel10.setText("Change Manager Account");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 150, 610, 60);

        jButton1.setText("<-- LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 110, 40);

        jButton3.setText("info");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1310, 720, 80, 40);

        ltitle.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        ltitle.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ltitle);
        ltitle.setBounds(530, 60, 420, 70);

        lpp.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lpp.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lpp);
        lpp.setBounds(960, 290, 180, 30);

        lp2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lp2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lp2);
        lp2.setBounds(960, 440, 190, 30);

        lp1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lp1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lp1);
        lp1.setBounds(970, 340, 180, 30);

        j1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg8.jpg"))); // NOI18N
        j1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j1MouseMoved(evt);
            }
        });
        getContentPane().add(j1);
        j1.setBounds(-10, 0, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed

        try
        {
            
         
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             
             String qry="Delete from login where desig='manager'";
            stmt.executeUpdate(qry);
           
        
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
        
        try
        {
            String g1,g2,g3;
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            g1=tu1.getText();
            g3=tu0.getText();
            if(g3.length()==0)
            {
                lpp.setText("Fill detail");
            }
            else
            {

                g2=new String(pf2.getPassword());

                String qry="insert into login values('"+g1+"','"+g2+"','manager','"+g3+"')";
                stmt.executeUpdate(qry);
                JOptionPane.showMessageDialog(this,"Manager Id and Password Changed");
                tu0.setText("");
                tu1.setText("");
                pf1.setText("");
                pf2.setText("");
                b5.setEnabled(false);
                pf1.setEditable(false);
                pf2.setEditable(false);
                pf2.setFocusable(false);
                pf2.setBackground(new java.awt.Color(204, 204, 204));
                pf1.setBackground(new java.awt.Color(204, 204, 204));
                lp1.setText("");
                lp2.setText("");
                lpp.setText("");
                tu0.requestFocus();

            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyReleased
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                b5.doClick();
            }   }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }     // TODO add your handling code here:
    }//GEN-LAST:event_b5KeyReleased

    private void pf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf2ActionPerformed

    private void pf2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf2KeyReleased
        try
        {
            String pa,pa2;
            pa=new String(pf1.getPassword());
            pa2=new String(pf2.getPassword());
            if(pa.equals(pa2))
            {
                lp2.setText("password matching");
                String j1=tu0.getText();
                String j2=tu1.getText();
                int k1=j1.length();
                int k2=j2.length();
                if((k1>0)&&k2>0)
                {
                    b5.setEnabled(true);
                }

            }
            else
            {
                lp2.setText("password not matching");
                b5.setEnabled(false);
            }
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                b5.doClick();
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_pf2KeyReleased

    private void tu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tu1ActionPerformed

    private void tu1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tu1KeyReleased
        try
        {
            String ss=tu1.getText();
            int len=ss.length();
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from login";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                String  pid=rs.getString("userid");
                if(ss.equals(pid)||(len==0))
                {
                    if(ss.equals(pid))
                    {
                        lp1.setText("Name exists");
                    }

                    pf1.setEditable(false);
                    pf2.setFocusable(false);
                    pf1.setBackground(new java.awt.Color(204, 204, 204));
                    pf2.setBackground(new java.awt.Color(204, 204, 204));

                    pf2.setEditable(false);
                    break;
                }
                else
                {
                    pf1.setEditable(true);
                    pf2.setEditable(true);
                    pf2.setFocusable(true);
                    pf1.setBackground(new java.awt.Color(255, 255, 255));
                    pf2.setBackground(new java.awt.Color(255, 255, 255));

                    lp1.setText("");
                }

            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tu1KeyReleased

    private void tu0KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tu0KeyReleased

        String pa,pa2;
        pa=new String(pf1.getPassword());
        pa2=new String(pf2.getPassword());
        if(pa.equals(pa2))
        {

            String j1=tu0.getText();
            String j2=tu1.getText();
            int k1=j1.length();
            int k2=j2.length();
            if((k1>0)&&k2>0)
            {
                b5.setEnabled(true);
            }

        }
        else
        {
            lp2.setText("password not matching");
            b5.setEnabled(false);
        }
        try
        {
            if(evt.getKeyCode() == KeyEvent.VK_TAB) {

                tu1.requestFocus();
                tu1.setText("ggwp");
            }}catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_tu0KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login ll=new login();
        ll.setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            jButton1.doClick();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        linfo.setVisible(true);
        linfo.setText("<html>\n" +
            "<head>\n" +
            "	<title>cafe</title>\n" +
            "</head>\n" +
            "<body><h1>gggggg</h1>\n" +
            "<p1> ggwp </p1>\n" +
            "\n" +
            "\n" +
            "</body>\n" +
            "</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void j1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseMoved
linfo.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_j1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageracc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageracc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageracc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageracc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageracc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b5;
    private javax.swing.JLabel j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel linfo;
    private javax.swing.JLabel lp1;
    private javax.swing.JLabel lp2;
    private javax.swing.JLabel lpp;
    private javax.swing.JLabel ltitle;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pf2;
    private javax.swing.JTextField tu0;
    private javax.swing.JTextField tu1;
    // End of variables declaration//GEN-END:variables
}
