import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saidu
 */
public class manager extends javax.swing.JFrame {
 static public String confirmpass=""; 
    /**
     * Creates new form manager
     */
    
    void showval()
    {
        
        try
        {
        DefaultTableModel tm=(DefaultTableModel)jt1.getModel();
        tm.setRowCount(0);

        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from items";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                String  pid=rs.getString("prodid");
                String pname=rs.getString("prodname");
                String cost=rs.getString("price");

                Object row[]={pid,pname,cost};
                tm.addRow(row);

            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
}catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }
    public manager(String password) {
        initComponents();
                linfo.setVisible(false);
                 jl.setIcon(new javax.swing.ImageIcon("C:\\bg.jpg"));
           try {

			
			FileInputStream fin = new FileInputStream("C:\\background.txt");
                        BufferedReader br=new BufferedReader(new InputStreamReader(fin));
String s1=br.readLine();
			

jl.setIcon(new javax.swing.ImageIcon(s1)); 

		} catch (IOException e) {
			
		} 

         Dimension sz=Toolkit.getDefaultToolkit().getScreenSize();
        setSize(sz.width,sz.height);
         showval();
         b5.setEnabled(false);
         pf1.setEditable(false);
         pf2.setEditable(false);
         pf2.setFocusable(false);
         confirmpass=password;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        linfo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        j3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        j2 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tu1 = new javax.swing.JTextField();
        pf1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pf2 = new javax.swing.JPasswordField();
        b5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        lp1 = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        j5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tu0 = new javax.swing.JTextField();
        jb2 = new javax.swing.JButton();
        b66 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        tu2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lp3 = new javax.swing.JLabel();
        by = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        lpp = new javax.swing.JLabel();
        lp5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText(" MANAGER ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 0, 140, 40);

        linfo.setBackground(new java.awt.Color(255, 255, 255));
        linfo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        linfo.setOpaque(true);
        getContentPane().add(linfo);
        linfo.setBounds(760, 120, 550, 600);

        jButton1.setText("<-- LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 110, 40);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Update Items");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 480, 230, 40);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 102));
        jLabel3.setText("item id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 150, 110, 50);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 102));
        jLabel4.setText("item name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 210, 90, 40);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 102));
        jLabel5.setText("cost");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 270, 70, 30);

        t3.setNextFocusableComponent(j3);
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t3KeyReleased(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(630, 270, 150, 30);

        t1.setNextFocusableComponent(t2);
        getContentPane().add(t1);
        t1.setBounds(630, 160, 150, 30);

        t2.setNextFocusableComponent(t3);
        getContentPane().add(t2);
        t2.setBounds(630, 210, 150, 30);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "ITEM NAME", "COST"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(920, 170, 420, 500);

        j3.setText("add -->");
        j3.setNextFocusableComponent(t4);
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        j3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j3KeyReleased(evt);
            }
        });
        getContentPane().add(j3);
        j3.setBounds(790, 210, 90, 30);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 102));
        jLabel6.setText("Item id");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 530, 110, 60);

        t4.setNextFocusableComponent(j2);
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t4KeyReleased(evt);
            }
        });
        getContentPane().add(t4);
        t4.setBounds(630, 420, 150, 30);

        j2.setText("Delete");
        j2.setNextFocusableComponent(t5);
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        j2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j2KeyReleased(evt);
            }
        });
        getContentPane().add(j2);
        j2.setBounds(800, 420, 90, 30);

        jb1.setText(" waiter details");
        jb1.setNextFocusableComponent(jb2);
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jb1KeyReleased(evt);
            }
        });
        getContentPane().add(jb1);
        jb1.setBounds(50, 570, 210, 50);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 290, 140, 70);

        tu1.setNextFocusableComponent(pf1);
        tu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu1ActionPerformed(evt);
            }
        });
        tu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tu1KeyReleased(evt);
            }
        });
        getContentPane().add(tu1);
        tu1.setBounds(150, 360, 170, 30);

        pf1.setBackground(new java.awt.Color(204, 204, 204));
        pf1.setNextFocusableComponent(pf2);
        getContentPane().add(pf1);
        pf1.setBounds(150, 410, 170, 30);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("confirm passsword");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 460, 160, 30);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 0));
        jLabel9.setText("passsword");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 410, 90, 30);

        pf2.setBackground(new java.awt.Color(204, 204, 204));
        pf2.setNextFocusableComponent(b5);
        pf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf2ActionPerformed(evt);
            }
        });
        pf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pf2KeyReleased(evt);
            }
        });
        getContentPane().add(pf2);
        pf2.setBounds(150, 460, 170, 30);

        b5.setText("Add Cashier");
        b5.setNextFocusableComponent(jb1);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b5KeyReleased(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(160, 500, 120, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(470, 40, 140, 10);

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 204));
        jLabel10.setText("Add Cashier");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 250, 130, 60);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 255));
        jLabel11.setText("Add new Items");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 80, 160, 60);

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(610, 0, 10, 50);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(-100, 240, 640, 20);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(630, 510, 130, 10);

        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(530, 50, 10, 710);

        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(460, 0, 10, 50);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(160, 290, 120, 10);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(630, 120, 150, 10);

        lp1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lp1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lp1);
        lp1.setBounds(340, 360, 180, 30);

        lp2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lp2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lp2);
        lp2.setBounds(330, 460, 190, 30);

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 255));
        jLabel12.setText("Delete Items");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(630, 340, 230, 60);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(630, 380, 120, 10);

        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 102));
        jLabel13.setText("cost");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(550, 580, 110, 60);

        jLabel15.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 102));
        jLabel15.setText("Item id");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(550, 410, 110, 60);

        t5.setNextFocusableComponent(t6);
        getContentPane().add(t5);
        t5.setBounds(630, 540, 150, 30);

        t6.setNextFocusableComponent(j5);
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t6KeyReleased(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(630, 590, 150, 30);

        j5.setText("Update");
        j5.setNextFocusableComponent(tu0);
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        j5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j5KeyReleased(evt);
            }
        });
        getContentPane().add(j5);
        j5.setBounds(800, 560, 90, 30);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 0));
        jLabel16.setText("User Id");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 340, 120, 70);

        tu0.setNextFocusableComponent(tu1);
        tu0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tu0KeyReleased(evt);
            }
        });
        getContentPane().add(tu0);
        tu0.setBounds(150, 310, 170, 30);

        jb2.setText("Edit Details");
        jb2.setNextFocusableComponent(b66);
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jb2KeyReleased(evt);
            }
        });
        getContentPane().add(jb2);
        jb2.setBounds(50, 640, 210, 50);

        b66.setText("BIll Details");
        b66.setNextFocusableComponent(t1);
        b66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b66ActionPerformed(evt);
            }
        });
        getContentPane().add(b66);
        b66.setBounds(290, 610, 210, 50);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(170, 120, 110, 10);

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 204));
        jLabel14.setText("Add waiter");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 80, 130, 60);

        tu2.setNextFocusableComponent(pf1);
        tu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu2ActionPerformed(evt);
            }
        });
        tu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tu2KeyReleased(evt);
            }
        });
        getContentPane().add(tu2);
        tu2.setBounds(140, 160, 170, 30);

        jLabel17.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 0));
        jLabel17.setText("Waiter Name:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 140, 120, 70);

        lp3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lp3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lp3);
        lp3.setBounds(320, 160, 180, 30);

        by.setText("Add Waiter");
        by.setEnabled(false);
        by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byActionPerformed(evt);
            }
        });
        getContentPane().add(by);
        by.setBounds(140, 210, 130, 25);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jSeparator11);
        jSeparator11.setBounds(-100, 540, 640, 20);

        lpp.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lpp.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lpp);
        lpp.setBounds(330, 310, 180, 30);

        lp5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lp5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lp5);
        lp5.setBounds(330, 380, 180, 30);

        jButton3.setText("info");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1310, 720, 80, 40);

        jl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg8.jpg"))); // NOI18N
        jl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMouseMoved(evt);
            }
        });
        getContentPane().add(jl);
        jl.setBounds(-10, 0, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
login ll=new login();
ll.setVisible(true);
setVisible(false);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt1MouseClicked

     

        // TODO add your handling code here:
    }//GEN-LAST:event_jt1MouseClicked

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed

        try
{
    int g3;
    String g1,g2;

              try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             g1=t1.getText();
             g2=t2.getText();
              g3=Integer.parseInt(t3.getText());
              int g4=Integer.parseInt(g1);
              
              if((g3<=0)||(g4<=0))
              {
                  int a=JOptionPane.showOptionDialog(null, "enter a valid value","error message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(a==JOptionPane.OK_OPTION)
                  {
                      t1.setText("");
                      t2.setText("");
                      t3.setText("");
                      t1.requestFocus();
                      
                      
                  }
                  
              }
              else
              {
                  String qry="insert into items values('"+g1+"','"+g2+"',"+g3+")";
                  stmt.executeUpdate(qry);
                  int c=JOptionPane.showOptionDialog(null, "Item Entered","Message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(c==JOptionPane.OK_OPTION)
                  {
                      t1.setText("");
                      t2.setText("");
                      t3.setText("");
                      t1.requestFocus();
                      
                      
                  }
              }
           
        
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
               
      
      
}
catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"enter valid values");
        }
        showval();

        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
 try
{
    
    String g4;

              try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             g4=t4.getText();
            String qry="delete from items where prodid='"+g4+"'";
            stmt.executeUpdate(qry);
            int a= stmt.getUpdateCount();
            if(a==0)
            {
            int b=JOptionPane.showOptionDialog(null, "item not found","error message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(b==JOptionPane.OK_OPTION)
                  {
                      t4.setText("");
                     
                      
                      
                  }
                  
            }
            else
            {
                int b=JOptionPane.showOptionDialog(null, "item deleted","Message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(b==JOptionPane.OK_OPTION)
                  {
                      t4.setText("");
                     t4.requestFocus();
                      
                      
                  }
            }
        
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
               
      
      
}
catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"enter valid values");
        }
        showval();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed

            try
                {
        JLabel jPassword = new JLabel("Password");
        JTextField password = new JPasswordField();
        Object[] ob = { jPassword, password};
        password.requestFocus();
        int result = JOptionPane.showConfirmDialog(null, ob, "Confirm Your Password", JOptionPane.DEFAULT_OPTION);
        password.requestFocus();
        
        if (result == JOptionPane.OK_OPTION) {
            
            String m = password.getText();
            if(m.equals(confirmpass))
{
    waiterdet a1=new waiterdet(confirmpass);
 a1.setVisible(true);
 setVisible(false);
}
else
{
    JOptionPane.showMessageDialog(this,"Wrong Password");
}
          
        }
        
        

        
   
        
}catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed

        
        
        
        try
        {
            String g1,g2,g3;
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             g1=tu1.getText();
              g3=tu0.getText();
             if(g3.length()==0)
             {
                 lpp.setText("Fill detail");
             }
             else
             {
             
             
             g2=new String(pf2.getPassword());
              
            String qry="insert into login values('"+g1+"','"+g2+"','cashier','"+g3+"')";
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(this,"Cashier added ");
            tu0.setText("");
            tu1.setText("");
            pf1.setText("");
            pf2.setText("");
            b5.setEnabled(false);
         pf1.setEditable(false);
         pf2.setEditable(false);
         pf2.setFocusable(false);
         pf2.setBackground(new java.awt.Color(204, 204, 204));
       pf1.setBackground(new java.awt.Color(204, 204, 204));
       lp1.setText("");
       lp2.setText("");
       lpp.setText("");
       tu0.requestFocus();
           
             }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void tu1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tu1KeyReleased
 try
        {
            String ss=tu1.getText();
            int len=ss.length();
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from login";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                String  pid=rs.getString("userid");
                if(ss.equals(pid)||(len==0))
                {
                    if(ss.equals(pid))
                    {
                        lp1.setText("Name exists");
                    }
                    
                    pf1.setEditable(false);
                    pf2.setFocusable(false);
                     pf1.setBackground(new java.awt.Color(204, 204, 204));
                      pf2.setBackground(new java.awt.Color(204, 204, 204));
                    
                      pf2.setEditable(false);
                      break;
                }
                else
                {
                     pf1.setEditable(true);
                      pf2.setEditable(true);
                      pf2.setFocusable(true);
                      pf1.setBackground(new java.awt.Color(255, 255, 255));
                      pf2.setBackground(new java.awt.Color(255, 255, 255));
                     
                        lp1.setText("");
                }
               

            }

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }   
 
// TODO add your handling code here:
    }//GEN-LAST:event_tu1KeyReleased

    private void pf2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf2KeyReleased
 try
 {
 String pa,pa2;
        pa=new String(pf1.getPassword());
pa2=new String(pf2.getPassword());
if(pa.equals(pa2))
{
    lp2.setText("password matching");
    String j1=tu0.getText();
    String j2=tu1.getText();
    int k1=j1.length();
    int k2=j2.length();
    if((k1>0)&&k2>0)
    {
      b5.setEnabled(true);  
    }
    
}
else
{
    lp2.setText("password not matching");
    b5.setEnabled(false);
}
if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      b5.doClick();
   }
}catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }

// TODO add your handling code here:
    }//GEN-LAST:event_pf2KeyReleased

    private void tu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tu1ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
 try
{
    
    String g4;
    int g5;

              try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             g4=t5.getText();
             g5=Integer.parseInt(t6.getText());
            if(g5<=0)
            {
                JOptionPane.showMessageDialog(this,"Enter valid input");
            }
            else
            {
            String qry="update items set price="+g5+" where prodid='"+g4+"'";
            stmt.executeUpdate(qry);
             int a=stmt.getUpdateCount();
             if(a==0)
            {
            int b=JOptionPane.showOptionDialog(null, "item not found","error message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(b==JOptionPane.OK_OPTION)
                  {
                      t5.setText("");
                     t6.setText("");
                     t5.requestFocus();
                      
                      
                  }
            
            }
            else
            {
                int b=JOptionPane.showOptionDialog(null, "Value Updated","Message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(b==JOptionPane.OK_OPTION)
                  {
                      t5.setText("");
                     t6.setText("");
                      t5.requestFocus();
                      
                  }
            }
           
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
        
               
      
      
}
catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"enter valid values");
        }
        showval();
        // TODO add your handling code here:
    }//GEN-LAST:event_j5ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
try
{
        JLabel jPassword = new JLabel("Password");
        JTextField password = new JPasswordField();
        Object[] ob = { jPassword, password};
        int result = JOptionPane.showConfirmDialog(null, ob, "Confirm Your Password", JOptionPane.DEFAULT_OPTION);
 
        if (result == JOptionPane.OK_OPTION) {
            
            String m = password.getText();
            if(m.equals(confirmpass))
{
    EditDetails a2=new EditDetails(confirmpass);
 a2.setVisible(true);
 setVisible(false);
}
else
{
    JOptionPane.showMessageDialog(this,"Wrong Password");
}
          
        }
        
      }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }  

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jb2ActionPerformed

    private void tu0KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tu0KeyReleased

 String pa,pa2;
        pa=new String(pf1.getPassword());
pa2=new String(pf2.getPassword());
if(pa.equals(pa2))
{
    
    String j1=tu0.getText();
    String j2=tu1.getText();
    int k1=j1.length();
    int k2=j2.length();
    if((k1>0)&&k2>0)
    {
      b5.setEnabled(true);  
    }
    
}
else
{
    lp2.setText("password not matching");
    b5.setEnabled(false);
}
        try
{
 if(evt.getKeyCode() == KeyEvent.VK_TAB) {
     
       tu1.requestFocus();
       tu1.setText("ggwp");
   }}catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
 // TODO add your handling code here:
    }//GEN-LAST:event_tu0KeyReleased

    private void t3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      j3.doClick();
      t1.requestFocus(true);
   }
        }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyReleased

    private void b5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      b5.doClick();
   }   }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }     // TODO add your handling code here:
    }//GEN-LAST:event_b5KeyReleased

    private void j3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j3KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      j3.doClick();
      t1.setFocusable(true);
   }     }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }   // TODO add your handling code here:
    }//GEN-LAST:event_j3KeyReleased

    private void j2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j2KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
     
   }  }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }     }//GEN-LAST:event_j2KeyReleased

    private void j5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j5KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
     
   } }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }// TODO add your handling code here:
    }//GEN-LAST:event_j5KeyReleased

    private void jb1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb1KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      jb1.doClick();
   } }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }       // TODO add your handling code here:
    }//GEN-LAST:event_jb1KeyReleased

    private void jb2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb2KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      jb2.doClick();
   } }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }       // TODO add your handling code here:
    }//GEN-LAST:event_jb2KeyReleased

    private void t4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyReleased
     try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String a=t4.getText();
            int b=a.length();
            if(b>0)
            {
      j2.doClick();
            }
      
   }
        }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_t4KeyReleased

    private void t6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyReleased
try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      String a=t6.getText();
            int b=a.length();
            if(b>0)
            {
      j5.doClick();
            }
   }
        }catch(Exception e)
         {
            JOptionPane.showMessageDialog(this, e.getMessage());
         }        // TODO add your handling code here:
    }//GEN-LAST:event_t6KeyReleased

    private void pf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf2ActionPerformed

    private void b66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b66ActionPerformed

        JLabel jPassword = new JLabel("Password");
        JTextField password = new JPasswordField();
        Object[] ob = { jPassword, password};
        int result = JOptionPane.showConfirmDialog(null, ob, "Confirm Your Password", JOptionPane.DEFAULT_OPTION);

        if (result == JOptionPane.OK_OPTION) {

            String m = password.getText();
            if(m.equals(confirmpass))
            {
                BillDetails a2=new BillDetails(confirmpass);
                a2.setVisible(true);
                setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Wrong Password");
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_b66ActionPerformed

    private void tu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tu2ActionPerformed

    private void tu2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tu2KeyReleased

        try
        {
            String ss=tu2.getText();
            int len=ss.length();
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
            String qry="Select * from login";
            ResultSet rs=stmt.executeQuery(qry);
            while(rs.next())
            {
                String  pid=rs.getString("userid");
                if(ss.equals(pid)||(len==0))
                {
                    if(ss.equals(pid))
                    {
                        lp3.setText("Name exists");
                    }
                    
                    by.setEnabled(false);
                    
                      break;
                }
                else
                {
                     by.setEnabled(true);
                     lp3.setText("");
                     
                }
              

            }
             if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      by.doClick();
   }
            

        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }   
 

 
        // TODO add your handling code here:
    }//GEN-LAST:event_tu2KeyReleased

    private void byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byActionPerformed

        
        
        
        try
        {
            int b=JOptionPane.showOptionDialog(null, "waiter added","Message",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,null,null);
                  if(b==JOptionPane.OK_OPTION)
                  {
            String g1,g2,g3;
            Class.forName("java.sql.DriverManager");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/cafe","root","ggwp");
            Statement stmt=conn.createStatement();
             g1="-";
              g3=tu2.getText();
             
             g2="-";
              
            String qry="insert into login values('"+g3+"','"+g1+"','waiter','"+g3+"')";
            stmt.executeUpdate(qry);
           // JOptionPane.showMessageDialog(this,"Waiter added ");
         
       tu2.setText("");
       tu2.requestFocus();
           
                  }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_byActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
      jButton1.doClick();
      
   }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        linfo.setVisible(true);
        linfo.setText("<html>\n" +
            "<head>\n" +
            "	<title>cafe</title>\n" +
            "</head>\n" +
            "<body><h1>gggggg</h1>\n" +
            "<p1> ggwp </p1>\n" +
            "\n" +
            "\n" +
            "</body>\n" +
            "</html>");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMouseMoved
linfo.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jlMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager(confirmpass).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b5;
    private javax.swing.JButton b66;
    private javax.swing.JButton by;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JLabel jl;
    private javax.swing.JTable jt1;
    private javax.swing.JLabel linfo;
    private javax.swing.JLabel lp1;
    private javax.swing.JLabel lp2;
    private javax.swing.JLabel lp3;
    private javax.swing.JLabel lp5;
    private javax.swing.JLabel lpp;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pf2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField tu0;
    private javax.swing.JTextField tu1;
    private javax.swing.JTextField tu2;
    // End of variables declaration//GEN-END:variables
}
